#!/bin/sh -e

SCRIPT=$(readlink $0 || true)
if [ -z $SCRIPT ]; then
    SCRIPT=$0
fi;

SCRIPT_DIR="$(cd "`dirname "$SCRIPT"`" && pwd -P)"
RELEASE_ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd -P)"
REL_NAME="{{ rel_name }}"
REL_VSN="{{ rel_vsn }}"
ERTS_VSN="{{ erts_vsn }}"

REL_DIR="$RELEASE_ROOT_DIR/releases/$REL_VSN"
ERTS_DIR="$RELEASE_ROOT_DIR/erts-$ERTS_VSN"

export BINDIR="$ERTS_DIR/bin"
export ROOTDIR="$RELEASE_ROOT_DIR"

export LD_LIBRARY_PATH="$ERTS_DIR/lib:$LD_LIBRARY_PATH"
ERTS_LIB_DIR="$ERTS_DIR/../lib"

cd "$RELEASE_ROOT_DIR"

"$BINDIR/erlexec" -config "$REL_DIR/sys.config" -boot "$REL_DIR/$REL_NAME" -boot_var ERTS_LIB_DIR "$ERTS_LIB_DIR" -args_file "$REL_DIR/vm.args" "$@"
